---
aws: 
  ami               : 'ami-aa8bfe9a'
  keypair_name      : 'fvoges'
  security_groups   : [ 'sg-2f24924a' ]
  region            : 'us-west-2'
  pemfile           : '~/.ssh/fvoges-puppetlabs-aws.pem'
  user_data         : "#!/bin/bash\necho 'Defaults:ec2-user !requiretty' > /etc/sudoers.d/999-vagrant-cloud-init-requiretty && echo 'Defaults:root !requiretty' >> /etc/sudoers.d/999-vagrant-cloud-init-requiretty && chmod 440 /etc/sudoers.d/999-vagrant-cloud-init-requiretty \n"
